# 12.1 Numeric Indexing


In [1]:
# arrays created using numeric indexing are copies of underlying data. 
import numpy as np

x = 10*np.arange(5.0)

In [2]:
x[[0]]

array([ 0.])

In [3]:
x[[0,2,1]]

array([  0.,  20.,  10.])

In [4]:
sel = np.array([4,2,3,1,4,4])

In [5]:
x[sel]

array([ 40.,  20.,  30.,  10.,  40.,  40.])

In [6]:
sel = np.array([[4,2],[3,1]])

In [7]:
x[sel]

array([[ 40.,  20.],
       [ 30.,  10.]])

In [8]:
# 2-dimensional array selection
x = np.reshape(np.arange(10.0),(2,5))
x

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [9]:
sel = np.array([0,1])
x[sel,sel]

array([ 0.,  6.])

In [10]:
x[sel,sel+1]

array([ 1.,  7.])

In [11]:
sel_row = np.array([[0,0],[1,1]])

In [12]:
sel_col = np.array([[0,1],[0,1]])

In [13]:
x[sel_row,sel_col]

array([[ 0.,  1.],
       [ 5.,  6.]])

In [14]:
sel_row = np.array([[0],[1]])

In [15]:
sel_col = np.array([[0,1]])

In [16]:
sel_col

array([[0, 1]])

In [17]:
sel_col.shape


(1, 2)

In [18]:
sel_row.shape

(2, 1)

In [19]:
x[sel_row,sel_col]

array([[ 0.,  1.],
       [ 5.,  6.]])

In [20]:
#12.1.1 Mixing numerical indexing with scalar selection
sel = np.array([[1],[2]])
x[0,sel]

array([[ 1.],
       [ 2.]])

In [21]:
sel_row = np.array([[0],[0]])
x[sel_row,sel]

array([[ 1.],
       [ 2.]])

In [22]:
#12.1.2 Mixing numerical indexing with Slicing. Allow the entire row selected. 
x[:,[1]]

array([[ 1.],
       [ 6.]])

In [23]:
x

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [24]:
x[[1],:]

array([[ 5.,  6.,  7.,  8.,  9.]])

In [25]:
x[:,1]

array([ 1.,  6.])

In [26]:
x = np.reshape(np.arange(3**3),(3,3,3))
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
sel1 = x[::2,[1,0],:1]
sel1

array([[[ 3],
        [ 0]],

       [[21],
        [18]]])

In [29]:
sel1.shape

(2, 2, 1)

In [30]:
x[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
x[0]# The first index is for height

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
x[:,0,:] # Selection of rows

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

In [34]:
x[:,:,0] # Selection of Columns

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [35]:
sel1 = x[[0,0],[1,0],:1]

In [36]:
step1 = x[:,:,:1]
step1

array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]])

In [37]:
step1.shape

(3, 3, 1)

In [42]:
step2 = step1[[0,0],[1,0],:]
step2

array([[3],
       [0]])

In [40]:
sel1

array([[3],
       [0]])

In [43]:
#12.1.3 Linear Numerical Indexing using flat
x.flat[3]

3

In [44]:
x.flat[[3,3]]

array([3, 3])

In [45]:
x.flat[[3,4,5]]

array([3, 4, 5])

In [46]:
x.flat

In [48]:
x.flat[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# 12.2 Logical Indexing

In [51]:
# Logical indices act as light switches and are either on or off. 
x = np.arange(-3,3)
x

array([-3, -2, -1,  0,  1,  2])

In [52]:
x<0

array([ True,  True,  True, False, False, False], dtype=bool)

In [53]:
x[x<0]

array([-3, -2, -1])

In [54]:
x[np.abs(x)>=2]

array([-3, -2,  2])

In [55]:
x = np.reshape(np.arange(-8,8),(4,4))
x

array([[-8, -7, -6, -5],
       [-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [56]:
x[x<0]

array([-8, -7, -6, -5, -4, -3, -2, -1])

In [59]:
x = np.reshape(np.arange(-8,8),(4,4))

In [60]:
x

array([[-8, -7, -6, -5],
       [-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [61]:
help(np.any)

Help on function any in module numpy.core.fromnumeric:

any(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean unless `axis` is not ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (`axis` = `None`) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        

In [62]:
cols = np.any(x<-6,0)

In [63]:
cols

array([ True,  True, False, False], dtype=bool)

In [64]:
rows = np.any(x<0,1)

In [65]:
rows

array([ True,  True, False, False], dtype=bool)

In [66]:
x

array([[-8, -7, -6, -5],
       [-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [67]:
np.any(x==-4,0)

array([ True, False, False, False], dtype=bool)

In [68]:
np.any(x==-4,1)

array([False,  True, False, False], dtype=bool)

In [69]:
x[cols,rows]

array([-8, -3])

In [70]:
np.ix_(cols,rows)

(array([[0],
        [1]], dtype=int64), array([[0, 1]], dtype=int64))

In [71]:
cols

array([ True,  True, False, False], dtype=bool)

In [72]:
rows

array([ True,  True, False, False], dtype=bool)

In [73]:
x[np.ix_(cols,rows)]

array([[-8, -7],
       [-4, -3]])

In [74]:
x

array([[-8, -7, -6, -5],
       [-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [75]:
#12.2.1 Mixing Ligical Indexing with Scalar Slection
np.sum(x,0)

array([-8, -4,  0,  4])

In [76]:
np.sum(x,0)>=0

array([False, False,  True,  True], dtype=bool)

In [77]:
x[0,np.sum(x,0)>=0]

array([-6, -5])

In [78]:
#12.2.2 Mixing Logical Indexing with Slicing
sel = np.sum(x<-1,0)>=2

In [79]:
sel

array([ True,  True,  True, False], dtype=bool)

In [80]:
x[:,sel]

array([[-8, -7, -6],
       [-4, -3, -2],
       [ 0,  1,  2],
       [ 4,  5,  6]])

In [81]:
#12.2.3 Mixing Logical Indexing with Numerical Indexing
sel = np.array([True,True,False,False])
sel.nonzero()

(array([0, 1], dtype=int64),)

In [82]:
x[[2,3],sel]

array([0, 5])

In [84]:
#12.2.4 Logical Indexing Functions
x = np.array([[1,2],[3,4]])
sel = x<=3
sel

array([[ True,  True],
       [ True, False]], dtype=bool)

In [85]:
indices = np.nonzero(sel)

In [86]:
indices

(array([0, 0, 1], dtype=int64), array([0, 1, 0], dtype=int64))

In [87]:
sel_temp = np.array([True,False])
np.nonzero(sel_temp)

(array([0], dtype=int64),)

In [88]:
x[indices]

array([1, 2, 3])

In [89]:
np.flatnonzero(sel)

array([0, 1, 2], dtype=int64)

In [90]:
# extract
x = np.random.randn(3)
x

array([ 0.81099828, -0.05728176, -0.17314216])

In [91]:
np.extract(x>0,x)

array([ 0.81099828])

In [92]:
x = np.random.randn(3,3)

In [93]:
np.extract(x>0,x)

array([ 1.07513983,  1.14899819,  0.92929658,  0.04122773,  1.86813787])

In [94]:
x

array([[ 1.07513983, -0.25796961,  1.14899819],
       [ 0.92929658, -2.64037435, -0.70288037],
       [ 0.04122773, -0.49567735,  1.86813787]])

In [95]:
x[x<0]

array([-0.25796961, -2.64037435, -0.70288037, -0.49567735])