# 8.1 Views

In [1]:
import numpy as np
x = np.arange(5)
type(x)

numpy.ndarray

In [2]:
x

array([0, 1, 2, 3, 4])

In [4]:
x.view(np.matrix)

matrix([[0, 1, 2, 3, 4]])

In [7]:
#asarray
x = np.random.randn(3,2)

In [8]:
y = np.asmatrix(x)
z = np.asarray(y)
type(z)

numpy.ndarray

# 8.2 Shape Information and Transformation


In [17]:
#shape
x = np.random.randn(4,3)
x

array([[-1.96701317,  0.32672886,  0.72799105],
       [ 0.28042817, -0.03097976, -0.29609772],
       [ 2.75305121, -0.44559168, -0.07366591],
       [ 0.62854188,  0.86576179, -0.6140971 ]])

In [18]:
x.shape=3,4

In [19]:
x

array([[-1.96701317,  0.32672886,  0.72799105,  0.28042817],
       [-0.03097976, -0.29609772,  2.75305121, -0.44559168],
       [-0.07366591,  0.62854188,  0.86576179, -0.6140971 ]])

In [20]:
x.shape = 6,-1

In [21]:
x.shape

(6, 2)

In [22]:
x

array([[-1.96701317,  0.32672886],
       [ 0.72799105,  0.28042817],
       [-0.03097976, -0.29609772],
       [ 2.75305121, -0.44559168],
       [-0.07366591,  0.62854188],
       [ 0.86576179, -0.6140971 ]])

In [24]:
x.shape=-1,6

In [25]:
x

array([[-1.96701317,  0.32672886,  0.72799105,  0.28042817, -0.03097976,
        -0.29609772],
       [ 2.75305121, -0.44559168, -0.07366591,  0.62854188,  0.86576179,
        -0.6140971 ]])

In [26]:
#reshape
x = np.array([[1,2],[3,4]])

In [27]:
y = np.reshape(x,(4,1))

In [28]:
y

array([[1],
       [2],
       [3],
       [4]])

In [29]:
#Size
x = np.random.randn(4,3)
np.size(x)

12

In [30]:
x.size

12

In [31]:
#ndim
np.ndim(x)

2

In [32]:
x.ndim

2

In [34]:
#tile
x = np.array([[1,2],[3,4]])
z = np.hstack((x,x,x))
y = np.vstack((z,z))
z
y

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [35]:
w = np.tile(x,(2,3))

In [36]:
w

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [37]:
y-w

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [38]:
#revel
x.ravel()

array([1, 2, 3, 4])

In [39]:
#flatten works much like ravel, only that it copies data. 
x.flatten()

array([1, 2, 3, 4])

In [40]:
x

array([[1, 2],
       [3, 4]])

In [41]:
y = x.flatten()

In [42]:
x[1]=5

In [47]:
y

array([1, 2, 3, 4])

In [48]:
x

array([[1, 2],
       [5, 5]])

In [49]:
x[0,0] = 4

In [50]:
x

array([[4, 2],
       [5, 5]])

In [51]:
x[1,1] = 3

In [52]:
x

array([[4, 2],
       [5, 3]])

In [54]:
#flat
x = np.array([[1,2],[3,4]])

In [55]:
x.flat

In [56]:
x.flat[2]

3

In [57]:
x.flat[:2]

array([1, 2])

In [58]:
#vstack, hstack. 
# This works similar with tile (above)

In [59]:
#concatenate
x

array([[1, 2],
       [3, 4]])

In [62]:
y = np.concatenate((x,x),axis=1)

In [63]:
y

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [64]:
# split, vsplit,hsplit
x = np.reshape(np.arange(20),(4,5))

In [65]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
y = np.vsplit(x,2)

In [67]:
y

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [69]:
type(y)

list

In [70]:
y[1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
y[0]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
# Delete
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
np.delete(x,1,0)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
np.delete(x,[2,3],1)

array([[ 0,  1,  4],
       [ 5,  6,  9],
       [10, 11, 14],
       [15, 16, 19]])

In [78]:
np.delete(x,np.arange(2),1)

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [79]:
# flipud and fliplr
x = np.reshape(np.arange(20),(5,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [80]:
np.flipud(x)

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [81]:
np.fliplr(x)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12],
       [19, 18, 17, 16]])

In [82]:
# diag
y = np.diag(x)

In [83]:
y

array([ 0,  5, 10, 15])

In [84]:
z = np.diag(y)
z

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [85]:
#triu, tril (lower/upper triangular arrays)
np.triu(x)

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 0,  0, 10, 11],
       [ 0,  0,  0, 15],
       [ 0,  0,  0,  0]])

In [86]:
np.tril(x)

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# 8.3 Linear Algebra Functions

In [88]:
x = np.matrix([[2,0],[0,4]])

In [92]:
import numpy.linalg as la
la.matrix_power(x,2)

matrix([[ 4,  0],
        [ 0, 16]])

In [93]:
x = np.matrix(np.reshape(np.arange(20),(5,4)))

In [94]:
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [95]:
la.svd(x)

(matrix([[-0.06412452, -0.77193785,  0.62621458,  0.08036255, -0.03737868],
         [-0.22469718, -0.49951094, -0.64142758,  0.24351066,  0.47882483],
         [-0.38526983, -0.22708403, -0.34889885, -0.14689469, -0.81036507],
         [-0.54584249,  0.04534288,  0.11722212, -0.7581928 ,  0.33377035],
         [-0.70641515,  0.31776979,  0.24688973,  0.58121428,  0.03514856]]),
 array([  4.96337102e+01,   2.54849186e+00,   1.61005564e-15,
          1.30753441e-16]),
 matrix([[-0.43989658, -0.47870789, -0.5175192 , -0.5563305 ],
         [ 0.71168181,  0.26615551, -0.17937079, -0.62489709],
         [ 0.54758936, -0.7211163 , -0.20053549,  0.37406242],
         [ 0.01207859, -0.4242538 ,  0.81227183, -0.40009662]]))

In [96]:
m,n,p = la.svd(x)

In [97]:
m

matrix([[-0.06412452, -0.77193785,  0.62621458,  0.08036255, -0.03737868],
        [-0.22469718, -0.49951094, -0.64142758,  0.24351066,  0.47882483],
        [-0.38526983, -0.22708403, -0.34889885, -0.14689469, -0.81036507],
        [-0.54584249,  0.04534288,  0.11722212, -0.7581928 ,  0.33377035],
        [-0.70641515,  0.31776979,  0.24688973,  0.58121428,  0.03514856]])

In [98]:
n

array([  4.96337102e+01,   2.54849186e+00,   1.61005564e-15,
         1.30753441e-16])

In [99]:
p

matrix([[-0.43989658, -0.47870789, -0.5175192 , -0.5563305 ],
        [ 0.71168181,  0.26615551, -0.17937079, -0.62489709],
        [ 0.54758936, -0.7211163 , -0.20053549,  0.37406242],
        [ 0.01207859, -0.4242538 ,  0.81227183, -0.40009662]])

In [100]:
m.shape

(5, 5)

In [101]:
n.shape

(4,)

In [102]:
p.shape

(4, 4)

In [105]:
#cond: measures how close to singular a matrix is. 
la.cond(x)

3.7959773506648115e+17

In [107]:
y = np.matrix([[1.0,0.5],[0.5,1]])
la.cond(y)

2.9999999999999991

In [109]:
#slodet: sign and log of determinant.
la.slogdet(y)

(1.0, -0.2876820724517809)

In [112]:
# solve: solve linear system. X is square and invertible 
X = np.matrix([[1.0,2,3],[3.0,3,4],[1.0,1,4]])
y = np.matrix([[1.0],[2.0],[3]])

In [111]:
la.solve(X,y)

matrix([[ 0.625],
        [-1.125],
        [ 0.875]])

In [113]:
# lstsq: least square solution of the linear system. 
X = np.random.randn(100,2)
y = np.random.randn(100)
la.lstsq(X,y)

(array([ 0.04229222, -0.06349116]),
 array([ 106.35584228]),
 2,
 array([ 10.757811  ,   9.47971978]))

In [114]:
# cholesky factor
x = np.matrix([[1,.5],[.5,1]])
C = la.cholesky(x)


In [115]:
x

matrix([[ 1. ,  0.5],
        [ 0.5,  1. ]])

In [116]:
C*C.T

matrix([[ 1. ,  0.5],
        [ 0.5,  1. ]])

In [117]:
#det
la.det(x)

0.75

In [118]:
# eig eigenvalues and eigenvectors. 
val,vec = la.eig(x)

In [119]:
val

array([ 1.5,  0.5])

In [120]:
vec

matrix([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]])

In [121]:
# eigh. If matrix is symmetric, then we can use eigh. 
la.eigh(x)

(array([ 0.5,  1.5]), matrix([[-0.70710678,  0.70710678],
         [ 0.70710678,  0.70710678]]))

In [122]:
# inv
xInv= la.inv(x)

In [123]:
xInv

matrix([[ 1.33333333, -0.66666667],
        [-0.66666667,  1.33333333]])

In [124]:
# trace 
np.trace(x)

2.0

In [125]:
la.matrix_rank(x)

2