In [2]:
x = []
type(x)

list

In [3]:
x = [[1,2,3,4],[5,6,7,8]]

In [5]:
x

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
x.append(5)

In [7]:
x


[[1, 2, 3, 4], [5, 6, 7, 8], 5]

In [8]:
y = [5,6]

In [9]:
x.extend(y)

In [10]:
x

[[1, 2, 3, 4], [5, 6, 7, 8], 5, 5, 6]

In [11]:
x.pop(2)

5

In [12]:
x

[[1, 2, 3, 4], [5, 6, 7, 8], 5, 6]

In [13]:
x.remove(5)

In [14]:
x

[[1, 2, 3, 4], [5, 6, 7, 8], 6]

**Tuples** 
Tuples is immutable. 

In [15]:
x = (0,1,2,3,4,5,6,7,8,9)
type(x)

tuple

### 3.2.6 Xrange (xrange) ###

handy for for loops. xrange is not technically a list, which is why the print(x) returns xrange(0,10). Technically xrange is an iterator which does not actually require the storage space of a list. range(10) will return a list. Best practice is to use xrange instead of range. 

### 3.2.7 Dictionary (dict) ###

Dictionaries keys must be unique primitive data types and values can contain any valide python data type. Values are accessed using keys. 


In [16]:
data = {'age':34,'children':[1,2],1:'apple'}

In [17]:
type(data)

dict

In [18]:
data['age']='xyz'
data['age']

'xyz'

In [19]:
data['name']='abc'
data

{'age': 'xyz', 1: 'apple', 'children': [1, 2], 'name': 'abc'}

In [20]:
# We can delete key value pair using reserved word del
del data['age']
data

{1: 'apple', 'children': [1, 2], 'name': 'abc'}

### 3.2.8 Sets (set, frozenset) ###

set and frozenset only differ in that the latter is immutable (so high performance), and so set is similar to a unique list while frozenset is similar to a unique tuple. 

In [21]:
x = set(['MSFT','GOOG','AAPL','HPQ','MSFT'])
x

{'AAPL', 'GOOG', 'HPQ', 'MSFT'}

In [22]:
x[1]

TypeError: 'set' object does not support indexing

In [23]:
y = list(x)

In [24]:
y

['AAPL', 'HPQ', 'MSFT', 'GOOG']

In [25]:
y[1]

'HPQ'

## 3.3 Python and Memory Management

When one variable is assigned to another, these will actually point to the same data in the computer's memory. To verify this, id() can be used to determine the unique identification number of a piece of data. 

In [26]:
x=1
y=x
id(x)

1410466288

In [27]:
id(y)

1410466288

# Chapter 4 Arrays and Matrices

## 4.1 Array

In [28]:
x = [0.0,1,2,3,4]

In [29]:
x

[0.0, 1, 2, 3, 4]

In [30]:
type(x)

list

In [32]:
import numpy as np
y = np.array(x)
y

array([ 0.,  1.,  2.,  3.,  4.])

In [33]:
type(y)

numpy.ndarray

### 4.1.1 Array dtypes

Python will try to use the minimum amount of memory to store the data. 

In [34]:
x = [0,1,2]
y = np.array(x)
y.dtype

dtype('int32')

In [35]:
# We can assign dtype as well
y = np.array(x,dtype='float64')
y.dtype

dtype('float64')

## 4.2 Matrix 

Matrices are essentialy a subset of arrays, and behave in a virtually identical manner. The two important differences are: 
- Matrices always have 2 dimensions. 
- Matrices follow the rules of linear algebra for *


In [36]:
x = np.matrix([1.0,2,3,4])
x

matrix([[ 1.,  2.,  3.,  4.]])

In [38]:
np.ndim(x)

2

## 4.3 1-dimensional Arrays

A vector is entered as a 1-dimensional array. 

## 4.4 2-dimensional Arrays

Matrices and 2-dimensional arrays are rows of columns. 


In [41]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

Because x is array, when we apply multiplication, it is element by element multiplication. 

In [44]:
y = np.asmatrix(x)
y*y

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

When we use asmatrix(), the multiplication follows the linear algebra. 

## 4.5 Multidimensional Arrays

Higher dimensional arrays are useful when tracking matrix valued process through time such as a time-varying covariance matrices. 

## 4.6 Concatenation

Concatenation is the process by which one vector or matrix is appended to another. Arrays and matrices can be concatenation horizontally or vertically. The inputs to concatenate must be grouped in tuple and the key word argument axis specifies whether the arrays are to be vertically (axis = 0) or horizontally (axis = 1) concatenated. 


In [46]:
x = np.array([[1.0,2],[3,4]])
y = np.array([[5.0,6],[7,8]])
z = np.concatenate((x,y),axis=0)
z

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [47]:
np.ndim(z)

2

## 4.7 Accessing Elements of an Array

Four methods are available. 
- Scalar selection
- Slicing
- Numerical Indexing
- Logical Indexing

We will introduce first two methods here because they are the simplest. Then we will look at the other two. 

### 4.7.1 Scalar Selection



In [49]:
x = np.array([1.0,2,3,4,5])
x[0]

1.0

### 4.7.2 Array Slicing


Arrays are sliced using the syntax [:,:,...,"]. 

In [51]:
x = np.array([1.0,2,3,5])
y = x[:]

In [52]:
y = x[:2]

In [53]:
y

array([ 1.,  2.])

Note that 2-dimensional slice syntax y[a:b,c:d] is the same as y[a:b,:][:,c:d] or y[a:b][:,c:d], although clearly the shorter form is preferred. 

In [54]:
y = np.array([[0.0,1,2,3,4],[5,6,7,8,9]])
y

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [56]:
y[:1,:]

array([[ 0.,  1.,  2.,  3.,  4.]])

In [57]:
y[:1]

array([[ 0.,  1.,  2.,  3.,  4.]])

In [58]:
y[:,:1]

array([[ 0.],
       [ 5.]])

In [59]:
y[:1,0:3]

array([[ 0.,  1.,  2.]])

In [61]:
y[:1][:,0:3]

array([[ 0.,  1.,  2.]])

### 4.7.3 Mixed Selection using Scalar and Slice Selectors 

When arrays have more than 1-dimension, it is often useful to mix scalar and slice selectors to select an entire row, column or panel of a 3-dimensional array. This is similar to pure slicing with one important caveat - dimensions selected using scalar selectors are eliminated. 

In [64]:
x = np.array([[1.0,2],[3,4]])
x[:1,:]


array([[ 1.,  2.]])

In [65]:
x[0,:]

array([ 1.,  2.])

This type of dimension reduction may matter when evaluating linear algebra expression. The principle adopted by NumPy is that slicing should always preserve the dimension of the underlying array, while scalar indexing should always collapse the dimension(s). 

### 4.7.4 Assignment using Slicing

Slicing and scalar selection can be used to assign arrays that have the same dimension as the slice. 


In [79]:
x = np.array([[0.0]*3]*3)

In [81]:
x

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [82]:
x[0,:]=np.array([1.0,2,3])

In [83]:
x

array([[ 1.,  2.,  3.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### 4.7.5 Linear Slicing using flat

Data in matrices is store in row-major order - elements are indexed by first counting across rows and then down columns. 

In [84]:
y = np.reshape(np.arange(25.0),(5,5))

In [85]:
y

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])

In [86]:
y[0]

array([ 0.,  1.,  2.,  3.,  4.])

In [87]:
y.flat[0]

0.0

In [88]:
y.flat[6]

6.0

In [89]:
y.flat[12:15]

array([ 12.,  13.,  14.])

In [90]:
x = np.arange(25.0)

In [91]:
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.])

 ## 4.8 Slicing and Memory Management
 
 Unlike lists, slices of arrays do not copy the underlying data. Instead a lice of an array returns a view of the array which shares thedata in the sliced array. 

In [93]:
x = np.reshape(np.arange(4.0),(2,2))

In [94]:
x

array([[ 0.,  1.],
       [ 2.,  3.]])

In [95]:
s1 = x[0,:]

In [96]:
s2 = x[:,0]

In [97]:
s1[0]=3.14

In [98]:
s1

array([ 3.14,  1.  ])

In [99]:
s2

array([ 3.14,  2.  ])

In [100]:
x

array([[ 3.14,  1.  ],
       [ 2.  ,  3.  ]])

If changes should not propagate to parent and sibling arrays, it is necessary to call copy on the slice. Alternatively, they can also be copied by calling array on arrays, or matrix on matrices. 

There is one notable exception to this rule - whenusing pure scalar selection the scalar valuereturned is always a copy. 

In [101]:
x = np.arange(5.0)
y = x[0]
z = x[:1]
y = -3.14
y

-3.14

In [102]:
x

array([ 0.,  1.,  2.,  3.,  4.])

In [103]:
z

array([ 0.])

In [104]:
z[0] = -2.79

In [105]:
y

-3.14

In [106]:
x

array([-2.79,  1.  ,  2.  ,  3.  ,  4.  ])

Finally, assignments from functions which change values will automatically create a copy of the underlying array. 

## 4.9 import and Modules

import can be used in a variety of ways. The simplest is to use from module import * which imports all functions in module. This method of using imort can be dangerous since if youuse it more than once, it is possible for functions to be hidden by later imports. A bettermethod is to just import the required functions. 


## 4.10 Calling functions

Functions calls have different conventions than most other expressions. The most important difference is that functions can take more than one input and return more than one output. The generic structure of a function call is out1,out2,out3,...=functionname(in1,in2,in3,...). Inputs and outputs are seperated by (,). 