# 11.1 >,>=,<,<=

In [1]:
import numpy as np
x = np.array([[1,2],[-3,-4]])
x >0 

array([[ True,  True],
       [False, False]], dtype=bool)

In [2]:
x ==-3

array([[False, False],
       [ True, False]], dtype=bool)

In [3]:
y = np.array([1,-1])

In [4]:
x<y

array([[False, False],
       [ True,  True]], dtype=bool)

In [5]:
y

array([ 1, -1])

# 11.2 and, or, not and xor

In [6]:
x = np.arange(-2.0,4)
y = x>=0
z = x<2

In [7]:
y

array([False, False,  True,  True,  True,  True], dtype=bool)

In [8]:
x

array([-2., -1.,  0.,  1.,  2.,  3.])

In [9]:
np.logical_and(y,z)

array([False, False,  True,  True, False, False], dtype=bool)

In [10]:
z

array([ True,  True,  True,  True, False, False], dtype=bool)

In [11]:
y & z

array([False, False,  True,  True, False, False], dtype=bool)

# 11.3 Multiple tests

In [13]:
# all and any
x = np.array([[1,2],[3,4]])
y = x<=2

In [14]:
y

array([[ True,  True],
       [False, False]], dtype=bool)

In [16]:
np.any(y)

True

In [ ]:
np.