## Operators

These are the standard operators: 
- Addition: '+'
- Subtraction: '-'
- Multiplication: '\*'
- Division: '/'
- Exponentiation: '\*\*'


In [1]:
x = 9
y = 5
(type(x),type(y))

(int, int)

In [2]:
x/y

1.8

# 5.2 Broadcasting

Under the normal rules of array mathematics, addition and subraction are only defined for arrays with the same shape or between an array and a scalar. For example, there is no obvious method to add 5-element vector and a 5 by 4 matrix. NumPy uses a technique called broadcasting to allow element-by-element mathematical operations on arrays (and matrices) which would not be compatible under standard rules of array mathematics. 

Suppose x is an m-dimnensional array with dimensions d=[d1,d2,...,dm], and y is an n-dimensional array with dimmensions f = [f1,f2,... fn] where m >= n. Formally, two arrays are broadcastable if the following conditions hold. 
1. if m>n, then treat y as a m-dimensional array and padding ones with dimension m-n. 
2. for i = 1,...,m, max(d_i,g_i)/min(d_i,g_i) belongs to {1,max(d_i,g_i)}


In [6]:
import numpy as np
x = np.array([[1,2,3.0]])
x

array([[ 1.,  2.,  3.]])

In [9]:
y = np.array([[0],[0],[0.0]])
y

array([[ 0.],
       [ 0.],
       [ 0.]])

In [10]:
x+y

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [15]:
x = np.reshape(np.arange(15),(3,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
x+y-x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [18]:
x+y-x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [19]:
y = np.arange(3)
y

array([0, 1, 2])

In [20]:
y.T

array([0, 1, 2])

In [21]:
np.asmatrix(y)

matrix([[0, 1, 2]])

In [22]:
z = np.asmatrix(y)

In [23]:
z.T

matrix([[0],
        [1],
        [2]])

In [24]:
z*z.T

matrix([[5]])

In [25]:
y = np.array([[0],[1],[2]])
y

array([[0],
       [1],
       [2]])

In [26]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
x+y-x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

# 5.3 Array and Matrix Addition (+) and Subtraction (-)

# 5.4 Array Multiplication (*)

The standard multiplication operator differs for variables with type array and matrix. For arrays, * performs element-by-element multiplication and so inputs must be broadcastable. For matrices, * is matrix multiplication as defined by linear algebra and there is no broadcasting. 
Conformable arrays can be multiplied according to the rules of matrix algebra using the function dot(). 

# 5.5 Matrix Multiplication (*)
multiply() performs element by element multiplication of matrices, and will use broadcasting if necessary. Matrices are identical to 2-dimensional arrays when performing element-by-element multiplication. 

# 5.6 Array and Matrix Division (/)
Division is always element by element and the rules of broadcasting are used. 

# 5.7 Array Exponentiation (**)
Array exponentiation operates element-by-element, and the rules of broadcasting are used. 

# 5.8 Matrix Exponentiation (**)
Matrix exponentiation differs from array exponentiation, and can only be used on square matrices. When x is a square matrix and y is a positive integer, x\*\*y produces x\*x\*..\*x (ytimes). When y is a negative integer, x\*\*y produces inv(x\*\*abs(y)) where `inv` produces the inverse.  

# 5.9 Parentheses
Parentheses can be used in the usual way to control the order in which mathematical expressions are evaluated, and can be nested to create complex expressions. See section 5.11 on Operator Precedence for more information on the order mathematical expression are evaluated. 
# 5.10 Transpose
Matrix transpose is expressed using either the `transpose` function, or the shortcut .T. For instance, if x is an *M* by *N* matrix, `transpose(x)`,x.`transpose()` and x.T are all its transpose. 
# 5.11 Operator Precedence
Computer math, like standard math, has operator precedence which determined how mathematical expression such as 2\*\*3+3\*\*2/7\*13 are evaluated. 