# 6.1 Generating Arrays and Matrices

**linspace**

`linspace(l,u,n)` generates a set of n points uniformly spaced between l, a lower bound (inclusive) and u, an upper bound (inclusive). 


In [3]:
import numpy as np
x = np.linspace(0,10,21)
x

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ])

**logspace**

`logspace(l,u,n)` produces a set of logarithmically spaced points. 

**arange**

`arange(l,u,s)` produces a set of points spaced by s between l, a lower bound(inclusive) and u, an upper bound (exclusive). 

**meshgrid**

`meshgrid` broadcasts two vectors to produce two 2-dimensional arrays, and is useful function when plotting 3-dimensional functions. 


In [4]:
x = np.arange(5)
y = np.arange(3)
X,Y = np.meshgrid(x,y)
X

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [5]:
Y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

**r_**

`r_` is a convenience function which generates 1-dimensional arrays from slice notation. 

**c_**

`c_` is virtually identical `r_` except that column arrays are generates, which are 2-dimensional (second dimension has size 1). 


In [7]:
np.c_[0:5:2]

array([[0],
       [2],
       [4]])

** ix_**

`ix_(a,b)` constructs an n-dimensional open mesh from n 1-dimensional lists or arrays. The output of ix_ is an n-element tuple containing 1-dimensional arrays. 

In [8]:
x = np.reshape(np.arange(25.0),(5,5))

In [9]:
x

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])

In [15]:
x[np.ix_([4,2],[0,1,2])]

array([[ 20.,  21.,  22.],
       [ 10.,  11.,  12.]])

In [16]:
x[[2,4],[0,1,2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

** mgrid **

`mgrid` is very similar to meshgrid but behaves like `r_` and `c_` in that it takes slicesd as input, and uses a real valued variable to denote step size and complex to denote number of values. The output is an n+1 dimensional vector where the first index of the output indexes the meshes. 

In [26]:
xx = np.mgrid[0:2:.5,0:2,0:3]
xx.ndim

4

# 6.2 Rounding

**around,round**

`around` rounds to the nearest integer, or to a particular decimal place when called with two arguments. 

In [28]:
x = np.random.randn(3)

In [29]:
np.around(x)

array([-0., -0., -1.])

In [30]:
np.around(x,2)

array([-0.22, -0.46, -0.7 ])

In [31]:
x.round(2)

array([-0.22, -0.46, -0.7 ])

** floor **

`floor` rounds to the next smallest integer. 

In [32]:
x = np.random.randn(3)

In [33]:
np.floor(x)

array([-1., -2., -1.])

** ceil **

`ceil` rounds to the next largest integer. 


In [37]:
x = np.random.randn(3)
x

array([ 0.93757058,  0.95501546,  1.39466226])

In [38]:
np.ceil(x)

array([ 1.,  1.,  2.])

# 6.3 Mathematics

** sum, cumsum ** 
`sum` sums elements in an arrya. By defualt, it will sum all elements in the array, and so the second argument is normally used to provide the axis to use -0 to sum down columns, 1 to sum across rows. `cumsum` produces the cumulative sum of the values in the array, and is also usually used with the second argument to indicate the axis to use. 

In [39]:
x = np.random.randn(3,4)
x

array([[ 0.44378769,  1.41413866,  0.61977208, -1.03114882],
       [-1.179892  , -0.65703154,  3.39665468, -2.03153381],
       [ 0.9397581 ,  3.54065581, -0.23534567,  0.16432705]])

In [40]:
np.sum(x) # All elements

5.3841422272439239

In [44]:
np.sum(x,0) # Down rows

array([ 0.20365378,  4.29776293,  3.78108109, -2.89835558])

In [45]:
np.sum(x,1) # Across Columns

array([ 1.44654961, -0.47180267,  4.40939529])

In [46]:
np.cumsum(x,0) # Down rows 

array([[ 0.44378769,  1.41413866,  0.61977208, -1.03114882],
       [-0.73610432,  0.75710712,  4.01642677, -3.06268263],
       [ 0.20365378,  4.29776293,  3.78108109, -2.89835558]])

`sum` and `cumsum` can both be used as function or as methods. When used as methods, the first input is the axis so that sum(x,0) is the same as x.sum(0). 

** prod, cumprod **

`prod` and `cumprod` behave similarly to sum and cumsum except that the product and cumulative product are returned, prod and cumprod can be called as function or methods. 

** diff **

`diff` computes the finite difference of a vector (also array) and returns n-1 element vctor when used on an n element vector. `diff` operates on the last axis by default, and so diff(x) operates across columns and returns x[:,1:size(x,1)]-x[:,:size(x,1)-1] for a 2-dimensional array. 

In [51]:
x = np.random.randn(3,2)

In [52]:
x

array([[ 2.43504496,  0.01874478],
       [-0.79257779, -0.70884712],
       [-0.29620005,  2.05786717]])

In [53]:
np.diff(x)

array([[-2.41630018],
       [ 0.08373067],
       [ 2.35406722]])

In [54]:
np.diff(x,1)

array([[-2.41630018],
       [ 0.08373067],
       [ 2.35406722]])

In [57]:
np.diff(x,axis=0)

array([[-3.22762276, -0.7275919 ],
       [ 0.49637775,  2.76671429]])

** exp **
`exp` returns the element by element exponential (e^x^) for an array. 

** log **

`log` returns the element by element natural logarithm (ln(x)) for an array. 

** log10 ** 

`log10` returns the element by element base-10 logarithm (log~10~(x)) for an array. 

** sqrt **

`sqrt` returns the element-by-element square root($\sqrt{x}$) for an array

** square **

`square` retunrs the element by element square (x^2^) for an array, and is equivalent to calling x\*\*2 when x is an array (but not a matrix). 

** absolute, abs **

`abs` and `absolute` retunrs the element by element absolute value for an array. 

** sign **

`sign` retunrs the element by element sign function, defined as 0 if x=0, and x/|x| otherwise. 


# 6.4 Complex Values

** real **

`real` retunrs real elements of a complex array. `real` can be called either as a function `real(x)` or as an attribute x.real. 

** imag **

`imag` retunrs the complex elements of a complex array. 



In [59]:
x = 2+3j
x

(2+3j)

In [60]:
np.real(x)


array(2.0)

In [61]:
x = np.array([2+3j,1-4j])

In [62]:
x

array([ 2.+3.j,  1.-4.j])

In [63]:
np.real(x)

array([ 2.,  1.])

In [64]:
np.imag(x)

array([ 3., -4.])

In [65]:
np.conj(x)

array([ 2.-3.j,  1.+4.j])

# 6.5 Set Functions


In [66]:
x = np.repeat(np.random.randn(3),(2))

In [67]:
x

array([-0.78341402, -0.78341402,  0.16485522,  0.16485522, -0.03542236,
       -0.03542236])

In [68]:
x.shape


(6,)

In [70]:
x.ndim

1

In [71]:
np.unique(x)

array([-0.78341402, -0.03542236,  0.16485522])

In [72]:
y,ind = np.unique(x,True)

In [73]:
ind

array([0, 4, 2], dtype=int64)

In [75]:
x.flat[ind]

array([-0.78341402, -0.03542236,  0.16485522])

In [77]:
x = np.arange(10.0)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [79]:
y = np.arange(5.0,15.0)
y

array([  5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.])

In [81]:
np.in1d(x,y)

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [82]:
np.intersect1d(x,y)

array([ 5.,  6.,  7.,  8.,  9.])

In [83]:
np.union1d(x,y)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.])

In [84]:
np.setdiff1d(x,y) # only returns elements in the first array, but not the second. 

array([ 0.,  1.,  2.,  3.,  4.])

In [85]:
np.setxor1d(x,y)

array([  0.,   1.,   2.,   3.,   4.,  10.,  11.,  12.,  13.,  14.])

# 6.6 Sorting and Extreme Values


In [86]:
x = np.random.randn(4,2)
x

array([[ 1.00300789,  0.23327035],
       [-0.66565702, -0.0521109 ],
       [ 0.0244107 , -1.99634042],
       [ 1.13553513, -0.53858602]])

In [87]:
np.sort(x)

array([[ 0.23327035,  1.00300789],
       [-0.66565702, -0.0521109 ],
       [-1.99634042,  0.0244107 ],
       [-0.53858602,  1.13553513]])

In [88]:
np.sort(x,0)

array([[-0.66565702, -1.99634042],
       [ 0.0244107 , -0.53858602],
       [ 1.00300789, -0.0521109 ],
       [ 1.13553513,  0.23327035]])

In [89]:
np.sort(x,1)

array([[ 0.23327035,  1.00300789],
       [-0.66565702, -0.0521109 ],
       [-1.99634042,  0.0244107 ],
       [-0.53858602,  1.13553513]])

In [90]:
np.sort(x,axis=None)

array([-1.99634042, -0.66565702, -0.53858602, -0.0521109 ,  0.0244107 ,
        0.23327035,  1.00300789,  1.13553513])

In [94]:
# ndarray.sort, argsort
x = np.random.randn(3)
x


array([ 1.61930998,  0.80618704,  1.09601699])

In [95]:
np.sort(x)

array([ 0.80618704,  1.09601699,  1.61930998])

In [96]:
x

array([ 1.61930998,  0.80618704,  1.09601699])

In [97]:
x.sort() # In-place, changes x

In [98]:
x

array([ 0.80618704,  1.09601699,  1.61930998])

In [99]:
#max, amax,argmax,min,amin,argmin
x = np.random.randn(3,4)
x

array([[-0.54112317, -0.07157795, -0.40631864, -1.45133117],
       [ 0.12501301, -0.67893673,  1.66114461, -0.13771132],
       [-0.17411441,  0.66486605,  0.27766278, -1.76796456]])

In [100]:
np.amax(x)

1.6611446136826025

In [101]:
x.max()

1.6611446136826025

In [102]:
x.max(0)

array([ 0.12501301,  0.66486605,  1.66114461, -0.13771132])

In [103]:
x.max(1)

array([-0.07157795,  1.66114461,  0.66486605])

In [104]:
np.amax(x,axis=0)

array([ 0.12501301,  0.66486605,  1.66114461, -0.13771132])

In [105]:
x.argmax(1)

array([1, 2, 1], dtype=int64)

In [106]:
x.argmax()

6

In [107]:
# minimum and maximumy 
y = np.random.randn(3,4)

In [108]:
np.maximum(x,y)

array([[-0.38351194,  0.88556492, -0.29744173,  1.13583897],
       [ 0.69480554,  0.02100228,  1.66114461,  0.32437233],
       [ 0.09130761,  0.71751588,  0.27766278, -0.24865655]])

# 6.7 Nan Function

In [111]:
x = np.random.randn(4)
x[1] = np.nan
x

array([-0.77174958,         nan,  0.29086242,  1.57299983])

In [112]:
np.sum(x)

nan

In [113]:
np.nansum(x)

1.0921126666404757

In [114]:
np.nansum(x)/np.sum(x[np.logical_not(np.isnan(x))])

1.0

In [115]:
np.logical_not(np.isnan(x))

array([ True, False,  True,  True], dtype=bool)

# 6.8 Functions and Methods/Properties
