This chapter divides into two main parts, one for Numpy and one for SciPy. 

# NumPy
# 19.1 Simulating Random Variables

In [4]:
# 19.1.1 Core random number generators
import numpy as np
x = np.random.rand(3,4,5)
y = np.random.random_sample((3,4,5))

In [5]:
m = np.random.randn(3,4,5)
n = np.random.standard_normal((3,4,5))

In [6]:
# uniform integer generators. 
p = np.random.randint(0,10,(100))
p.max()

9

In [8]:
q = np.random.random_integers(0,10,(100))
q.max()

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  if __name__ == '__main__':


10

In [11]:
#19.1.2 Random Array Functions
x = np.arange(10)
np.random.shuffle(x)
x

array([4, 0, 9, 3, 1, 8, 6, 2, 7, 5])

In [16]:
#19.1.3 Select Random Number Generators
x = np.random.binomial(1,0.5,(10,10))
x


array([[1, 1, 1, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 0, 1, 1, 0, 1, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 1, 1, 0]])

There are a lot of random number generators in different prob distribution. Remember to search reference. 

In [17]:
#19.2.3 Replicating Simulation Data. 
# Call seed(s) at the start of the program. 

# 19.3 Statistics Functions
mean, std, cov, ...

# SciPy
# 19.4 Continuous Random Variables

In [20]:
import scipy as sp
import scipy.stats as stats

In [22]:
x = stats.norm.rvs(loc=0,scale=1,size=(1,10))
x

array([[ 0.07215172, -0.03310868, -0.71943919,  0.40487164,  1.77814479,
        -0.89159313,  0.46205702, -0.40381124,  1.40299969,  0.31944111]])

In [24]:
y = stats.norm.pdf([0.5,-0.5])
y

array([ 0.35206533,  0.35206533])

In [27]:
y = stats.norm.cdf([0.5,-0.5])
y

array([ 0.69146246,  0.30853754])

## 19.4.2 Important Distributions

norm,beta,cauchy, chi2, expon, exponpow, f, gamma, laplace, lognorm, t. 

# 19.5 Select Statistical Functions

In [28]:
#mode, moment, skew, kurtosis, pearsonr, spearmanr, 
x = np.random.randn(10,3)

In [29]:
spearmanr = stats.spearmanr
rho,pval = spearmanr(x)

In [30]:
rho

array([[ 1.        , -0.24848485, -0.16363636],
       [-0.24848485,  1.        , -0.32121212],
       [-0.16363636, -0.32121212,  1.        ]])

In [34]:
rho,pval = spearmanr(x[:,1],x[:,2])
rho

-0.32121212121212117

In [35]:
x[:,1]

array([ 1.36817448,  0.95988117, -0.1014471 , -2.03177728, -1.4554407 ,
        0.59742187,  0.20624777,  0.3706026 , -0.66840794, -1.392178  ])

In [36]:
x = np.random.randn(10)
y = x+np.random.randn(10)
linregress = stats.linregress
slope,intercept,rvalue,pvalue,stderr = linregress(x,y)
slope

1.4456758502545

In [37]:
rsquare = rvalue**2
rsquare

0.72399824745577268

In [38]:
x.shape

(10,)

In [39]:
x.shape=10,1

In [40]:
y.shape=10,1

In [42]:
z = np.hstack((x,y))

In [43]:
linregress(z)

LinregressResult(slope=1.4456758502545, intercept=-0.21406678447527083, rvalue=0.85088086560679732, pvalue=0.0017997109079018856, stderr=0.31558263291689248)

# 19.6 Select Test

In [44]:
x = np.random.randn(100)
kstest = stats.kstest

In [45]:
stat,pval = kstest(x,'norm')
stat

0.18708057798907807

In [46]:
pval

0.0015457468053328149

In [ ]:
ncdf = stats.norm