In [7]:
import numpy as np

In [8]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
n=4
u = np.zeros((n,1))
for i in range (n):
    u[i] = math.exp(a[i])

In [12]:
u

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692],
       [54.59815003]])

In [13]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [15]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [16]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)


[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [17]:
A.shape

(3, 4)

In [18]:
cal.shape

(4,)

In [19]:
cal.T

array([ 59. , 239. , 155.4,  76.9])

In [20]:
cal

array([ 59. , 239. , 155.4,  76.9])

In [21]:
cal.T.shape

(4,)

In [22]:
a = np.random.randn(5)
print(a)

[-2.90422715  0.39845592 -0.37050865 -0.69268283  0.75229074]


In [23]:
print(a.shape)

(5,)


In [24]:
a = np.random.randn(5,1)
print(a)

[[ 0.44457157]
 [-0.43784564]
 [ 0.90103401]
 [ 0.04651993]
 [-0.55028082]]


In [25]:
print(a.T)

[[ 0.44457157 -0.43784564  0.90103401  0.04651993 -0.55028082]]


In [27]:
print(np.dot(a,a.T))

[[ 0.19764388 -0.19465372  0.4005741   0.02068144 -0.2446392 ]
 [-0.19465372  0.19170881 -0.39451382 -0.02036855  0.24093806]
 [ 0.4005741  -0.39451382  0.81186228  0.04191604 -0.49582173]
 [ 0.02068144 -0.02036855  0.04191604  0.0021641  -0.02559902]
 [-0.2446392   0.24093806 -0.49582173 -0.02559902  0.30280898]]
